config/routes.rb
Rails.application.routes.draw do
  resources :details do
    resources :reservations, except: [:destroy] do
      member do
        put 'confirm'
      end
    end
    collection do
      get 'find_details'
    end
  end
  
  resources :reservations, only: [:destroy]

  devise_for :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  root 'welcome#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :detail
  
  before_validation :generate_slug
  validates :slug, presence: true, uniqueness: true
  
  def to_param
    self.slug
  end
  
  def can_confirm?
    self.status == 'Submitted' 
  end
  
  def can_edit?
    self.status != 'Success' 
  end
  
  def generate_slug
    if (self.slug.blank?)
      begin
        count = (count ||= 0) + 1        
        new_slug = ActiveSupport::Inflector.transliterate("#{detail.slug} #{reserved_date} #{count}").
                              strip.
                              gsub("-","").
                              gsub(" ","-").
                              gsub(":","").
                              gsub(",","").
                              gsub("'","").                                                            
                              downcase

      end until (new_slug and !(reservation = Reservation.find_by_slug(new_slug)))
      self.slug = new_slug
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  respond_to :html

  def index
    @detail = Detail.find_by_slug(params[:detail_id])
    @reservations = @detail.reservations
    respond_with(@detail, @reservations)
  end

  def show
    @detail = Detail.find_by_slug(params[:detail_id])
    @reservations = @detail.reservations
    respond_with(@reservation)
  end

  def new
    @reservation = Reservation.new
    @reservation.detail = Detail.find_by_slug(params[:detail_id])
    respond_with(@reservation)
  end

  def edit
  end
  
  def confirm
    if current_user && params[:selected_card] 
      @reservation = Reservation.find_by_slug(params[:id])
      detail  = Detail.find_by_slug(params[:detail_id])
      
      
      amount = @reservation.seats * detail.per_head_charge
      response, transaction = current_user.purchase(params[:selected_card], amount)
      
      transaction.reservation = @reservation
      transaction.status = response.message
      
      transaction.save
      
      if response.success?
        @reservation.status = 'Success'
        @reservation.number = generate_reservation_number
      else
        @reservation.status = 'Failed'
      end
      
      @reservation.save
      
      respond_with(@reservation)
        
    end
  end
  
  def generate_reservation_number
    begin
      count = (count ||= 0) + 1        
      new_reservation_number = "#{(0...5).map { current_user.email.chars.to_a[rand(current_user.email.size)] }.join}-#{count}"
    end until (new_reservation_number and !(reservation = Reservation.find_by_number(new_reservation_number)))
    new_reservation_number
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.detail = Detail.find_by_slug(params[:detail_id])
    @reservation.user = current_user
    @reservation.status = 'Submitted'
    # response = current_user.purchase(params[:payment_id], params[:amount])
#     if response.success?
#       @reservation.save
#     end
    @reservation.save
    respond_with(@reservation.detail, @reservation)
  end

  def update
    @reservation.update(reservation_params)
    respond_with(@reservation.detail, @reservation)
  end

  def destroy
    detail = @reservation.detail
    @reservation.destroy
    # redirect_to :action => "index"
    redirect_to detail_reservations_path(detail, detail.reservations, format: :html)
    # respond_with(detail, detail.reservations)
  end

  private
    def set_reservation
      @reservation = Reservation.find_by_slug(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:seats, :reserved_date, :reserved_time)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.haml
= simple_form_for [@reservation.detail, @reservation]  do |f|
  = f.error_notification
  .row
    .small-5.columns
  .row
    .small-3.columns
      = f.label :seats, class: 'right inline'
    .small-9.column
      = f.text_field :seats
  .row
    .small-3.columns
      = f.label :reserved_date, class: 'right inline'
    .small-9.column
      = f.text_field :reserved_date
  .row
    .small-3.columns
      = f.label :reserved_time, class: 'right inline'
    .small-9.column
      = f.text_field :reserved_time
  .row
    .small-1
      = f.submit "Reserve", class: 'button round'

app/views/reservations/confirm.html.haml
%h1 Reservation has been confirm. 

= @reservation.status 
= @reservation.number

= link_to 'Do another reservation', new_detail_reservation_path(@reservation.detail)

app/views/reservations/edit.html.haml
%h1 Editing reservation

= render 'form'

= link_to 'Show', detail_reservation_path(@reservation.detail, @reservation)
\|
= link_to 'Back', detail_reservations_path

app/views/reservations/index.html.haml
%h1 Listing reservations

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @reservations.each do |reservation|
      %tr
        %td= reservation.number
        %td= reservation.reserved_date
        %td= reservation.reserved_time
        %td= reservation.seats
        %td= link_to 'Detail', detail_reservation_path(reservation.detail, reservation)

= link_to 'New Reservation', new_detail_reservation_path

app/views/reservations/new.html.haml
%h1 New reservation

= render 'form'

= link_to 'Back', detail_reservations_path

app/views/reservations/show.html.haml
%p#notice= notice

.row
  = form_tag(confirm_detail_reservation_path, method: "put") do
    .small-5.columns
      .row
        .small-3.columns
          = label_tag 'Reserved seats', nil, class: 'right inline'
        .small-9.column
          = text_field_tag 'name',@reservation.seats,placeholder: 'Enter name here...',disabled: true
      .row
        .small-3.columns
          = label_tag 'Reserved date', nil, class: 'right inline'
        .small-9.column
          = text_field_tag 'reserved_date',@reservation.reserved_date,placeholder: 'Enter name here...',disabled: true
      .row
        .small-3.columns
          = label_tag 'Reserved time', nil, class: 'right inline'
        .small-9.column
          = text_field_tag 'reserved_time',@reservation.reserved_time,placeholder: 'Enter name here...',disabled: true
      .row
        .small-3.columns
          = label_tag 'Reserved Status', nil, class: 'right inline'
        .small-9.column
          = text_field_tag 'reservation_status',@reservation.status,placeholder: '...',disabled: true

      - if @reservation.can_confirm?
        .row
          .small-12.columns
            - current_user.payment_profiles.each do |pf|
              = radio_button_tag 'selected_card', pf.payment_profile_id
              = pf.card_number          

      - if @reservation.can_edit?
        = link_to 'Edit', edit_detail_reservation_path(@reservation.detail, @reservation)
        \|
      = link_to 'Back', detail_reservations_path
      
      - if @reservation.can_confirm?      
        = submit_tag 'Pay to confirm'