config/routes.rb
Rails.application.routes.draw do
  resources :details do
    resources :reservations, except: [:destroy] do
      member do
        put 'confirm'
      end
    end
    collection do
      get 'find_details'
    end
  end
  
  resources :reservations, only: [:destroy]

  devise_for :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  root 'welcome#index'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  
  has_attached_file :photo,
                    styles: { medium: "300x300>", thumb: "100x100>", small: "50*50>" },
                    default_url: ":rails_root/public/assets/products/:id/:style/:basename.:extension"
                 
  has_many :addresses
  has_many :reservations
  has_and_belongs_to_many :cuisines
  has_and_belongs_to_many :food_types
  
  accepts_nested_attributes_for :reservations
  
  before_validation :generate_slug
  validates :slug, presence: true, uniqueness: true

  
  
  

  validates_attachment_content_type :photo, content_type: ['image/jpeg', 'image/png']
  validates_attachment_size :photo, less_than: 5.megabytes
  CURRENT_TIME = Time.now
 # 
  # scope :by_hours_from, ->(hours_from) { where('extract(hour from hours_from) > :hour', { hour: hours_from }) }
#generate_scope

  def time_duration
    duration_ary = []
    [CURRENT_TIME].tap { 
            |array| array << round_to(array.last) + 30.minutes while array.last < (round_to(hours_to) - 1.hour) 
    }.each{|time|  duration_ary << "#{time.hour}:#{time.min}"}
  end 
  
  def round_to(min=15)
    Time.at((CURRENT_TIME.to_r/min*60).round  * (min*60))
  end
  
  def to_param
    self.slug
  end
  
  def generate_slug
    unless self.slug
      begin
        count = (count ||= 0) + 1 
        new_slug = ActiveSupport::Inflector.transliterate("#{name} #{count}").
                                  strip.
                                  gsub("-","").
                                  gsub(" ","-").
                                  gsub(":","").
                                  gsub(",","").
                                  gsub("'","").                                                            
                                  downcase
      end until (new_slug and !(detail = Detail.find_by_slug(new_slug)))
      self.slug = new_slug
    end
  end
end
 

app/controllers/details_controller.rb
require "#{Rails.root}/app/services/detail_finder"


class DetailsController < ApplicationController
  # load_and_authorize_resource
  before_action :set_detail, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, unless: [:index]

  respond_to :html

  def index
    puts current_user
    @filter = params[:detail_filter] || {}
    @details = Services::DetailFinder.find_dataset(@filter)
    respond_with(@details)
  end

  def show
    respond_with(@detail)
  end

  def new
    @detail = Detail.new
    respond_with(@detail)
  end

  def edit
  end
  
  def reserve
    user = User.first
    
  end
  
  def find_details
    Services::DetailFinder.find_dataset(params)
  end

  def create
    @detail = Detail.new(detail_params)
    @detail.save
    respond_with(@detail)
  end

  def update
    @detail.update(detail_params)
    respond_with(@detail)
  end

  def destroy
    @detail.destroy
    respond_with(@detail)
  end

  private
    def set_detail
      @detail = Detail.find_by_slug(params[:id])
    end

    def detail_params
      params.require(:detail).permit(:name, :hours_from, :hours_to, :price_from, :price_to, :photo)
    end
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_detail.html.haml
%div
  .row
    = detail.name
    = detail.price_from
    = link_to 'Reserve', new_detail_reservation_path(detail), class: 'button round'
    = link_to 'Edit', edit_detail_path(detail), class: 'button round'
    

app/views/details/_form.html.haml
= form_for @detail, :html => { :multipart => true } do |f|
  - if @detail.errors.any?
    #error_explanation
      %h2= "#{pluralize(@detail.errors.count, "error")} prohibited this detail from being saved:"
      %ul
        - @detail.errors.full_messages.each do |msg|
          %li= msg		  
  .row
    .small-5.columns
      .row
        .small-3.columns
          = f.label :name, class: 'right inline'
        .small-9.column
          = f.text_field :name
      .row
        .small-3.columns
          = f.label :hours_from, class: 'right inline'
        .small-9.column
          = f.text_field :hours_from
      .row
        .small-3.columns
          = f.label :hours_to, class: 'right inline'
        .small-9.column
          = f.text_field :hours_to
      .row
        .small-3.columns
          = f.label :price_from, class: 'right inline'
        .small-9.column
          = f.text_field :price_from
      .row
        .small-3.columns
          = f.label :price_to, class: 'right inline'
        .small-9.column
          = f.text_field :price_to
      .row
        .small-3.columns
        .small-9.column
          = f.file_field :photo
      .row
        .small-11
        .small-1
          = f.submit "Save", class: 'button round'
	  	

app/views/details/edit.html.haml
%h1 Editing detail

= render 'form'

= link_to 'Show', @detail
\|
= link_to 'Back', details_path

app/views/details/index.html.haml
/ %ul.small-block-grid-2.small-block-grid-3.small-block-grid-4
/   - @details.each do |detail|
/     - if detail.photo.exists?
/       %li
/         = link_to image_tag(detail.photo.url), detail

.row
  .small-3.columns
    %h3 Detail Filter
    = form_tag("/details", method: "get") do
      = text_field_tag 'detail_filter[name]', @filter[:name], placeholder: 'Enter name here...'
      = radio_button_tag 'detail_filter[price_sort]' , 'high_to_low', @filter[:price_sort] == 'high_to_low' 
      = radio_button_tag 'detail_filter[price_sort]' , 'low_to_high', @filter[:price_sort] == 'low_to_high' 
      = submit_tag 'Search'
  .small-9.columns
    = render @details
    
        

app/views/details/new.html.haml
%h1 New detail

= render 'form'

= link_to 'Back', details_path

app/views/details/show.html.haml
.row
  .small-5.columns
    .row
      .small-3.columns
        = label_tag 'name', nil, class: 'right inline'
      .small-9.column
        = text_field_tag 'name',@detail.name,placeholder: 'Enter name here...',disabled: true
    .row
      .small-3.columns
        = label_tag 'hours_from', 'Hours From', class: 'right inline'
      .small-9.column
        = text_field_tag 'hours_from',@detail.hours_from,placeholder: 'Enter starting of hours here...', disabled: true
    .row
      .small-3.columns
        = label_tag 'hours_to', 'Hours To', class: 'right inline'
      .small-9.column
        = text_field_tag 'hours_to',@detail.hours_to,placeholder: 'Enter ending of hours here...', disabled: true
    .row
      .small-3.columns
        = label_tag 'price_from', 'Pirce From', class: 'right inline'
      .small-9.column
        = text_field_tag 'price_from',@detail.price_from,placeholder: 'Enter starting of price here...', disabled: true
    .row
      .small-3.columns
        = label_tag 'price_to', 'Price To', class: 'right inline'
      .small-9.column
        = text_field_tag 'price_to',@detail.price_to,placeholder: 'Enter end of price here...', disabled: true
    .row
      .small-12
        = image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@detail.addresses.first.try(:latitude)}%2C#{@detail.addresses.first.try(:longitude)}"
    .row
      .small-12
        = link_to 'Edit', edit_detail_path(@detail), class: 'button round'
        = link_to 'Back', details_path, class: 'button round'
    
    
/ %p#notice= notice
/
/ %p
/   %b Image
/   = image_tag @detail.photo.url(:medium)
/ %p
/   %b Name:
/   = @detail.name
/ %p
/   %b Hours from:
/   = @detail.hours_from
/ %p
/   %b Hours to:
/   = @detail.hours_to
/ %p
/   %b Price from:
/   = @detail.price_from
/ %p
/   %b Price to:
/   = @detail.price_to

/ = link_to 'Edit', edit_detail_path(@detail)
/ \|
/ = link_to 'Back', details_path